### PR TITLE
Fix kqueue for platforms where C's long is i32

### LINKED ISSUE #946: mio 0.6.17 compilation error on apple ios targets
Mio version 0.6.17 fails to compile on `apple-ios-i386` and `armv7s-apple-ios` with the following error:

```
error[E0277]: the trait bound `i32: std::convert::From<u32>` is not satisfied
  --> /Users/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.17/src/sys/unix/kqueue.rs:77:26
   |
77 |                 tv_nsec: libc::c_long::from(to.subsec_nanos()),
   |                          ^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<u32>` is not implemented for `i32`
   |
   = help: the following implementations were found:
             <i32 as std::convert::From<bool>>
             <i32 as std::convert::From<i16>>
             <i32 as std::convert::From<i8>>
             <i32 as std::convert::From<std::num::NonZeroI32>>
           and 2 others
   = note: required by `std::convert::From::from`
```

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Same as #947, but for the v0.6.x branch.

Fixes #946.

/cc @carllerche since this might need a release (see #946).

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
The failure on FreeBSD is about using `ATOMIC_USIZE_INIT` over `AtomicUsize::new`, thus unrelated.

File: src/sys/unix/kqueue.rs [hunk 1]
```diff
@@ -74,7 +74,9 @@ impl Selector {
         let timeout = timeout.map(|to| {
             libc::timespec {
                 tv_sec: cmp::min(to.as_secs(), time_t::max_value() as u64) as time_t,
-                tv_nsec: libc::c_long::from(to.subsec_nanos()),
+                // On some platforms C's long is i32, for those we need to ensure
+                // `subsec_nanos` doesn't overflow.
+                tv_nsec: cmp::min(to.subsec_nanos(), libc::c_long::max_value() as u32) as libc::c_long,
```
Comment (Thomasdezeeuw) [inline src/sys/unix/kqueue.rs]: The only thing I'm unsure of is `c_long::max_value() as u32` with 64 bit long.

**Comment by Thomasdezeeuw** [comment]
@asomers this is the same as #947, can you review this as well?

**Comment by Thomasdezeeuw** [comment]
@carllerche How do you want to deal with the deprecation warning? Leave it or shall I added an `allow(deprecated)` attribute?

**Comment by asomers** [comment]
I'm confused.  I don't know why that deprecated warning is only showing up for FreeBSD.  `src/lib.rs` contains a `#![allow(deprecated)]` line, and both the FreeBSD and Linux tests are using the same compiler version.

**Comment by asomers** [comment]
@Thomasdezeeuw I see the problem now.  Your branch doesn't include 5e39b5836d04173b6f3e269a4e574398b1731179 .  That's why the FreeBSD build is complaining about deprecation.  Rebase your branch and that warning should go away.

**Comment by Thomasdezeeuw** [comment]
I've rebased. I thinking I was using an outdated branch.
