### PR TITLE
Document unconnected TcpStream returned by TcpStream::connect

### LINKED ISSUE #1523: Proper handling of ErrorKind::NotConnected
Windows, mio 0.7.13

When I try to `read()` from a `TcpStream` opened to an address that can't be connected to (e.g, on my box `telnet 10.20.30.70 5010` reports *Connecting...* for a loong time), the `read` returns `ErrorKind::NotConnected`. When trying to `read` again, it returns the same error again. However, it might eventually connect (it might just take some time for the connection to be established), so this is not a fatal error, just a state of the connection. 

So, what is the proper handling of `NotConnected`? Two options come to my mind:

 1. `read()` repeatedly until the connection is established or fails with a hard error. Spin-locking `read()`s consumes CPU, so it looks like a terrible idea. 
 2. `poll()`. But, the mio documentation states that *Once a readiness event is received, the corresponding operation must be performed repeatedly until it returns WouldBlock. Unless this is done, there is no guarantee that another readiness event will be delivered, even if further data is received for the event source.*. So, I get it that I should **only** `poll()` when I get an explicit `ErrorKind::WouldBlock`, otherwise it is dangerous because I may not be delivered a crucial readiness event.

Btw, on Linux, I do not get `NotConnected` in such case at all.

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Closes #1523

/cc @dvtomas

### CODE REVIEW

File: src/net/tcp/stream.rs [hunk 1]
```diff
@@ -49,6 +49,30 @@ pub struct TcpStream {
...
+    ///
+    ///  1. Call `TcpStream::connect`
+    ///  2. Register the returned stream with at least [read interest].
+    ///  3. Wait for a (readable) event.
+    ///  4. Check `TcpStream::peer_addr`. If it returns `libc::EINPROGRESS` or
+    ///     `ErrorKind::NotConnected` it means the stream is not yet connected,
+    ///     go back to step 3. If it returns an address it means the stream is
+    ///     connected, go to step 5. If another error is returned something
+    ///     whent wrong.
+    ///  5. Now the stream can be used.
```
Comment (Darksonn) [inline src/net/tcp/stream.rs:73]: This doesn't match what Tokio is doing (we don't use `peer_addr`). Is Tokio doing it incorrectly?

**Review by Darksonn — APPROVED** [review]

File: src/net/tcp/stream.rs (hunk 1 above)
Comment (Thomasdezeeuw) [reply src/net/tcp/stream.rs:73]: On modern Unix you can also so `SO_ERROR`, but I'm not sure what OSs do and don't work with it. Honestly this whole non-blocking connect is pretty messy.
