### PR TITLE
 Don't leak file descriptors if registering Waker fails

### LINKED ISSUE #1031: Possible fd-leak in `eventfd::Waker::new`
https://github.com/tokio-rs/mio/blob/eadafc2bed0c8d8f10e527f8cf25fac606e1fdfc/src/sys/unix/waker.rs#L24-L26

A call to `selector.register` can actually fail, hence the `?`, but in an error case we would not destroy the `eventfd` handle which results in a rare-case fd-leak.

EDIT:

Same thing here:

https://github.com/tokio-rs/mio/blob/eadafc2bed0c8d8f10e527f8cf25fac606e1fdfc/src/sys/unix/waker.rs#L129

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Thanks to @cynecx for finding these problems.

Fixes #1031 and #1032.

### CODE REVIEW

File: src/sys/unix/waker.rs [hunk 1]
```diff
@@ -21,16 +20,18 @@ mod eventfd {
...
         pub fn new(selector: &Selector, token: Token) -> io::Result<Waker> {
-            let fd = syscall!(eventfd(0, libc::EFD_CLOEXEC | libc::EFD_NONBLOCK))?;
-
-            selector.register(fd, token, Interests::READABLE)?;
-            Ok(Waker {
-                fd: unsafe { File::from_raw_fd(fd) },
+            syscall!(eventfd(0, libc::EFD_CLOEXEC | libc::EFD_NONBLOCK)).and_then(|fd| {
+                // Turn the file descriptor into a file first so we're ensured
+                // it's closed when dropped, e.g. when register below fails.
+                let file = unsafe { File::from_raw_fd(fd) };
```
Comment (carllerche) [inline src/sys/unix/waker.rs]: Do we want to define our own type that takes an `Fd` and calls `close` on drop? That might be a bit more reliable?

Comment (Thomasdezeeuw) [reply src/sys/unix/waker.rs]: On Unix that is exactly what `File` is and since it's not exposed anywhere I would argue that the extra code doesn't outweigh the benefits.

Comment (carllerche) [reply src/sys/unix/waker.rs]: The primary danger, though low probability, is the drop impl starts adding file specific syscalls. Up to you though, I approved.

Comment (Thomasdezeeuw) [reply src/sys/unix/waker.rs]: I guess that could be the case, let's tackle that when it comes up.
